name: Deploy to AWS ECS

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY: hello-react-flask
  ECS_CLUSTER: hello-cluster
  ECS_SERVICE: hello-service
  CONTAINER_NAME: hello-container

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # --------------------------
    # AWS Auth
    # --------------------------
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    # --------------------------
    # Login to ECR
    # --------------------------
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    # --------------------------
    # Build + Push Docker Image
    # --------------------------
    - name: Build Docker image
      run: docker build -t $ECR_REPOSITORY .

    - name: Tag image
      run: |
        docker tag $ECR_REPOSITORY:latest \
        ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:latest

    - name: Push image to ECR
      run: |
        docker push \
        ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:latest

    # --------------------------
    # Update ECS service with new image
    # --------------------------
    - name: Deploy to ECS
      run: |
        aws ecs update-service \
          --cluster $ECS_CLUSTER \
          --service $ECS_SERVICE \
          --force-new-deployment
